org: zegheim
app: slapbot
service: slapbot
frameworkVersion: '2'
configValidationMode: error
useDotenv: true
variablesResolutionMode: '20210326'
unresolvedVariablesNotificationMode: error
deprecationNotificationMode: error
provider:
  name: aws
  stage: dev
  region: us-east-1
  memorySize: 128
  runtime: python3.9
  timeout: 3 
  logRetentionInDays: 7
  lambdaHashingVersion: 20201221
  httpApi:
    payload: '2.0'
    cors: true
    authorizers:
      TokenAuthorizer:
        type: request
        functionName: TokenAuthorizer
        resultTtlInSeconds: 0
        enableSimpleResponses: true
        payloadVersion: '2.0'
functions:
  SlapBot:
    handler: handler.bot_command
    description: Slap your friends in Telegram and more!
    events:
      - httpApi:
          method: POST
          path: /slap/{token}
          authorizer:
            name: TokenAuthorizer
    environment:
      TELEGRAM_BOT_HANDLE: ${env:TELEGRAM_BOT_HANDLE}
  TokenAuthorizer:
    handler: handler.authorize
    name: TokenAuthorizer
    description: Authorizes SlapBot to access AWS Lambda.
    environment:
      TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
plugins:
  - serverless-python-requirements
custom:
    pythonRequirements:
      usePoetry: true
      dockerizePip: true
